// Starter data for the Cigar Log.
// You can edit this file directly, or use the Add cigar button in the browser.
// Browser-added cigars are saved to localStorage and can be exported/imported as JSON.
const CIGARS = [
  {
    id: 'cle-connecticut-robusto',
    name: 'CLE CONNECTICUT ROBUSTO',
    status: 'smoked',
    quantity: 0,
    brand: 'C.L.E.',
    company: 'C.L.E. Cigar Company',
    madeIn: 'Honduras',
    vitola: 'Robusto',
    strength: '2',
    rating: '',
    boughtDate: '',
    smokedDate: '',
    price: '',
    wrapperLeaf: 'Connecticut',
    wrapperOrigin: 'Ecuador',
    binderLeaf: '',
    binderOrigin: 'Honduras',
    fillerLeaf: '',
    fillerOrigin: 'Honduras',
    taste: 'Creamy, pepper, nuts',
    draw: '',
    burn: '',
    nicotine: '',
    pairing: '',
    notes: 'Already smoked. Add your personal rating and what you remember from it.',
    link: 'https://obchod.cigarovysvet.sk/product/cle-connecticut-robusto/',
    imageFile: 'CLE CONNECTICUT ROBUSTO.png',
    createdAt: '2026-07-09T20:00:00.000Z'
  },
  {
    id: 'rocky-patel-vintage-1990-robusto-rounded',
    name: 'ROCKY PATEL VINTAGE 1990 ROBUSTO ROUNDED',
    status: 'owned',
    quantity: 1,
    brand: 'Rocky Patel',
    company: 'Rocky Patel Premium Cigars',
    madeIn: 'Honduras',
    vitola: 'Robusto Rounded',
    strength: '3',
    rating: '',
    boughtDate: '',
    smokedDate: '',
    price: '',
    wrapperLeaf: 'Maduro',
    wrapperOrigin: '',
    binderLeaf: '',
    binderOrigin: 'Nicaragua',
    fillerLeaf: '',
    fillerOrigin: 'Honduras',
    taste: 'Nuts, coffee, caramel',
    draw: '',
    burn: '',
    nicotine: '',
    pairing: '',
    notes: 'In humidor. Good candidate to compare against your milder Connecticut cigars.',
    link: 'https://obchod.cigarovysvet.sk/product/rocky-patel-vintage-1990-robusto-rounded/',
    imageFile: 'ROCKY PATEL VINTAGE 1990 ROBUSTO ROUNDED.png',
    createdAt: '2026-07-09T20:01:00.000Z'
  },
  {
    id: 'simon-beltre-cuatro-caminos-toro',
    name: 'SIMON BELTRE CUATRO CAMINOS TORO',
    status: 'owned',
    quantity: 1,
    brand: 'Simón Beltré',
    company: 'Simón Beltré',
    madeIn: 'Dominican Republic',
    vitola: 'Toro',
    strength: '3',
    rating: '',
    boughtDate: '',
    smokedDate: '',
    price: '',
    wrapperLeaf: '',
    wrapperOrigin: 'Ecuador',
    binderLeaf: 'Olor Dominicano',
    binderOrigin: 'Dominican Republic',
    fillerLeaf: 'Semilla 20.20, San Vicente, Negrito, SVM',
    fillerOrigin: 'Dominican Republic',
    taste: 'Pepper, cream, wood, sweetness, vanilla',
    draw: '',
    burn: '',
    nicotine: '',
    pairing: '',
    notes: 'In humidor. Looks like a useful Dominican comparison cigar.',
    link: 'https://obchod.cigarovysvet.sk/product/simon-beltre-cuatro-caminos-toro',
    imageFile: 'SIMON BELTRE CUATRO CAMINOS TORO.png',
    createdAt: '2026-07-09T20:02:00.000Z'
  },
  {
    id: 'dias-de-gloria-robusto',
    name: 'DIAS DE GLORIA ROBUSTO',
    status: 'owned',
    quantity: 1,
    brand: 'A.J. Fernandez',
    company: 'A.J. Fernandez Cigar Co.',
    madeIn: 'Nicaragua',
    vitola: 'Robusto',
    strength: '2',
    rating: '',
    boughtDate: '',
    smokedDate: '',
    price: '',
    wrapperLeaf: 'Habano',
    wrapperOrigin: 'Nicaragua',
    binderLeaf: '',
    binderOrigin: 'Nicaragua',
    fillerLeaf: '',
    fillerOrigin: 'Nicaragua',
    taste: 'Cedar, earthy tobacco, cocoa, pepper',
    draw: '',
    burn: '',
    nicotine: '',
    pairing: '',
    notes: 'In humidor. Good Nicaragua reference cigar for your log.',
    link: 'https://obchod.cigarovysvet.sk/product/dias-de-gloria-robusto',
    imageFile: 'DIAS DE GLORIA ROBUSTO.png',
    createdAt: '2026-07-09T20:03:00.000Z'
  }
];
